FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
COPY src ./src
RUN uv pip install --system --no-cache .

# Принудительно ставим scikit-learn той же версии, на которой обучалась модель
RUN pip install --no-cache-dir "scikit-learn==1.7.2"

# Модели монтируются томом при запуске контейнера:
#   -v ${PWD}\models:/app/models

EXPOSE 8000

CMD ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]


